sudo: false
language: python
python: 2.7
env:
  - PLONE_VERSION="4"
  - PLONE_VERSION="5"
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis-${PLONE_VERSION}.cfg
  - bin/buildout -N -t 3 -c travis-${PLONE_VERSION}.cfg
script: bin/test
